### ISSUE TITLE
When I reopen the program the "enable auto accept" option is turned back to disabled.

### ISSUE THREAD

**Issue by Neinndall** [sweetriverfish/LeagueAutoAccept#1]
Hello! Today I started to use this, for the zeri pick zeri. 

I don't know if it's a bug, but when I set the auto accept option to ON, when I close the program and reopen it, it appears disabled, I don't know if it keeps the last user options.

**Comment by sweetriverfish** [comment]
There's a setting to save your last selected champion and spells as well as the settings themselves however it is not meant to keep the enabled part on and thus it doesn't. You think it should?

Perhaps I could add another setting to enable the auto accept on startup?

**Comment by sweetriverfish** [comment]
Well I ended up simply making the existing setting apply to the "enable auto accept" option. Feel free to download the latest version.

Let me know if I can close this

**Comment by Neinndall** [comment]
Thx! Any errors, I'll let you know!
