### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by SabDabz86** [sweetriverfish/LeagueAutoAccept#10]
It doesn't accept queue at all just idles also I've downloaded dotnet 7 x64 and x86 running as admin as well maybe needs a update?

**Comment by sweetriverfish** [comment]
I'm not quite sure what you mean by that. I tested it and everything seems to be working fine. Could you please provide me with more details so that I can better understand the issue you're experiencing?

**Comment by SabDabz86** [comment]
it works now nevermind

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
