### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by brrbrrry** [sweetriverfish/LeagueAutoAccept#12]
I'm trying to write my own script for mac but it won't click in the league client window is that due to perms or league client not allowing automation?

**Comment by brrbrrry** [comment]
I did give terminal and python perms in s+p accesibility

**Comment by sweetriverfish** [comment]
- My app doesn't do any clicks, I don't know how to implement that
- I don't know how to use python
- I don't know how Mac OS works
