### ISSUE TITLE
Add minimize to system tray

### ISSUE THREAD

**Issue by quy3501** [sweetriverfish/LeagueAutoAccept#13]

**Comment by sweetriverfish** [comment]
Do you want a button that will do that or some setting that will automatically minimize it to system tray every time you click the minimize button?

What's the purpose? Saving space on the taskbar?

**Comment by quy3501** [comment]
I want asetting that will minimize it to system tray every time you click the minimize button and a setting to start the program automatically minimized to system tray
> What's the purpose? Saving space on the taskbar?

Yes

**Comment by sweetriverfish** [comment]
I did some research and it seems like this is not (easily) possible with a console app because it lacks built in functionality to interact with the system tray. I will close this as I will probably not be implementing it like that.
