### ISSUE TITLE
Tutorial for dummies pls

### ISSUE THREAD

**Issue by Phoeniq** [sweetriverfish/LeagueAutoAccept#16]
Hey,

could you make a tutorial showing how to start the whole thing?
Unfortunately, I am not familiar with programming na dstuff like that.

**Comment by sweetriverfish** [comment]
1. download compiled `.exe` file from releases
2. open it

As noted in the readme file - If the application fails to launch, chances are you don't have .NET Runtime installed. You can find the latest version at https://dotnet.microsoft.com/en-us/download/dotnet/7.0

**Comment by Phoeniq** [comment]
Sry but which one is the compiled .exe? i can't find it or am i blind?

**Comment by sweetriverfish** [comment]
https://github.com/sweetriverfish/LeagueAutoAccept/releases/download/v3.3/Leauge.Auto.Accept.exe

**Comment by Phoeniq** [comment]
Thank you :)
