### ISSUE TITLE
Instant chat message not working properly

### ISSUE THREAD

**Issue by hutigh** [sweetriverfish/LeagueAutoAccept#17]
Hello, chat message does not work for me.
In fact it did work if i start League Auto Accept while the champ select is already here.
I suppose it is bcause my pc is too slow and it didnt write the message in time.
Is it possible to add for the next version a timer like you already did for the ban et champ selec ?

**Comment by sweetriverfish** [comment]
I assume I could just make it verify that you are connect to chat before sending a chat message, will do it some day

**Comment by hutigh** [comment]
Okay thx !

**Comment by sweetriverfish** [comment]
@hutigh hey, I have made some potential fix, could you compile it and test if it works?

**Comment by hutigh** [comment]
Hello ! I ll test it later today thx !

**Comment by hutigh** [comment]
> @hutigh hey, I have made some potential fix, could you compile it and test if it works?

Sorry i'm pretty noob about it, i got an error while trying to compile it i got this error idk how to change the kit sdk : Code NETSDK1045 can you tell me how do i change the .net sdk kit to 7.0 or 6.0 ?

**Comment by sweetriverfish** [comment]
I think you just need to download the SDK which you probably don't have installed? idk but try it
https://dotnet.microsoft.com/en-us/download/visual-studio-sdks
The app is currently using .NET 7 so get both [x64](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.400-windows-x64-installer) and [x86](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.400-windows-x86-installer) for .NET 7 and try again

**Comment by sweetriverfish** [comment]
Any update?

**Comment by hutigh** [comment]
Hello sorry I didn't had  time to play recently I ll try this weekend!

**Comment by hutigh** [comment]
Hello ! i finally got some time to try it, i see my chat in the champ select but my 2 friends with me in the champ select didnt saw it

**Comment by sweetriverfish** [comment]
Thanks for testing.

I think they probably joined champ select late? I thought about it before and I'm not sure what to do. I can either make it wait for everyone to join which might cause the message to be delayed too long or I can make it resend it every time someone rejoins but that sounds too spammy. Should I just add 100ms fixed delay and call it a day?

**Comment by hutigh** [comment]
yeah i think adding 100 ms should be just fine tell me when its done and i ll try it

**Comment by sweetriverfish** [comment]
Done. I tested it with a friend and he could see the message. Let me know if you are satisfied with it.

**Comment by hutigh** [comment]
Thx you ! I can't test it until next week end (this weekend I will be at lec final yeah !) I'll let you know if it works and I'll close the thread !

**Comment by ttttttttoby98** [comment]
I compiled it myself and in 99% of the cases it works. Just for people with really bad connection not. Thanks for the improvement

**Comment by sweetriverfish** [comment]
Since op has not been responding and I assume the fix is working well enough I'll just close it as is
