### ISSUE TITLE
why i get ban for this?

### ISSUE THREAD

**Issue by trikiman** [sweetriverfish/LeagueAutoAccept#18]
![image](https://github.com/sweetriverfish/LeagueAutoAccept/assets/39918652/d2254863-4d64-456c-a2c4-8f5043ba56f2)

**Comment by sweetriverfish** [comment]
The game ID that this ban mentions is an intro bot game played on EUW last year at October 10th, at around 10:12 AM Germany time, in which there were two accounts being botted, two of which were also active today. I assume one of them is yours.

Have you bought your account? Does your nickname happen to be Laemkin or Turvesban? Your account is botted.
If you don't want to get banned, don't buy botted accounts, and don't bot them yourself either.

![Screenshot 2023-07-25 214956](https://github.com/sweetriverfish/LeagueAutoAccept/assets/13397494/372f9e26-5a48-4d0c-a647-18417319b5cb)
![Screenshot 2023-07-25 214958](https://github.com/sweetriverfish/LeagueAutoAccept/assets/13397494/b0623611-0cc4-4c8a-9d58-d5204743b06b)

**Comment by trikiman** [comment]
> The game ID that this ban mentions is an intro bot game played on EUW last year at October 10th, at around 10:12 AM Germany time, in which there were two accounts being botted, two of which were also active today. I assume one of them is yours.
> 
> Have you bought your account? Does your nickname happen to be Laemkin or Turvesban? Your account is botted. If you don't want to get banned, don't buy botted accounts, and don't bot them yourself either.
> 
> ![Screenshot 2023-07-25 214956](https://user-images.githubusercontent.com/13397494/256006068-372f9e26-5a48-4d0c-a647-18417319b5cb.png) ![Screenshot 2023-07-25 214958](https://user-images.githubusercontent.com/13397494/256006117-b0623611-0cc4-4c8a-9d58-d5204743b06b.png)

how u find this game id? can u share with program or what u use.

**Comment by trikiman** [comment]
> Laemkin

ye my is Laemkin i have another 3 acc and they didnt banned.

**Comment by sweetriverfish** [comment]
They may get banned later on if you bought them too, Riot is doing ban waves for botted accounts atm

**Comment by trikiman** [comment]
> The game ID that this ban mentions is an intro bot game played on EUW last year at October 10th, at around 10:12 AM Germany time, in which there were two accounts being botted, two of which were also active today. I assume one of them is yours.
> 
> Have you bought your account? Does your nickname happen to be Laemkin or Turvesban? Your account is botted. If you don't want to get banned, don't buy botted accounts, and don't bot them yourself either.
> 
> ![Screenshot 2023-07-25 214956](https://user-images.githubusercontent.com/13397494/256006068-372f9e26-5a48-4d0c-a647-18417319b5cb.png) ![Screenshot 2023-07-25 214958](https://user-images.githubusercontent.com/13397494/256006117-b0623611-0cc4-4c8a-9d58-d5204743b06b.png)

Can you tell me the program you use?
