### ISSUE TITLE
Pls add an option (split) only for insta ban and insta pick / lock

### ISSUE THREAD

**Issue by KasaiKonoru** [sweetriverfish/LeagueAutoAccept#20]
I mean I want to enable insta ban but not insta pick

**Comment by sweetriverfish** [comment]
Done, will be released with the next update whenever that is. (feel free to compile your own build)

**Comment by KasaiKonoru** [comment]
Oh thank you so much.
Yeahhh. Im not the best in C#

**Comment by sweetriverfish** [comment]
Are you talking about compiling? You just need to open the solution in the latest Visual Studio and click the build button. I can upload one if you'd like?

**Comment by KasaiKonoru** [comment]
yes pls. I will also learn it later when I have more time

**Comment by sweetriverfish** [comment]
https://send.vis.ee/download/876a57f8302be4f3/#zSX8UE8WLNjfWYR3ex-Qag

**Comment by KasaiKonoru** [comment]
thanks <3

**Comment by KasaiKonoru** [comment]
But I have a question. When I build this with the solution file. I can't use the exe without the dll in the same folder.
![image](https://github.com/sweetriverfish/LeagueAutoAccept/assets/45830738/5d060f48-7faa-434b-a8d1-e52db41d7372)

**Comment by sweetriverfish** [comment]
![Screenshot (1114)](https://github.com/sweetriverfish/LeagueAutoAccept/assets/13397494/4f11e7c7-3ce5-422b-a928-f7ba862c00ce)

**Comment by KasaiKonoru** [comment]
thank you
