### ISSUE TITLE
Feature Request: automatically re-queue after sitting in queue for a few minutes

### ISSUE THREAD

**Issue by hm** [sweetriverfish/LeagueAutoAccept#21]
Could you add the ability to auto queue up for a game and also limit the time that you stay in queue before leaving and re-entering queue? I learned somewhere that leaving and re-entering queue before the estimated time (typically around 2-3mins) the client shows as estimated gives you a higher chance of getting your main role(s). I've been doing this manually with success anecdotally and think it would nice to be able to automate this process :)

**Comment by sweetriverfish** [comment]
Done, will be released with the next update.
