### ISSUE TITLE
rune page

### ISSUE THREAD

**Issue by trikiman** [sweetriverfish/LeagueAutoAccept#24]
can u plz add rune change? sometimes i forgot to change it and play with wrong runes(

**Comment by sweetriverfish** [comment]
you do realize that if I added something to changes runes you'd still have to manually configure it, right?

**Comment by trikiman** [comment]
> you do realize that if I added something to changes runes you'd still have to manually configure it, right?

i have main page, and main champ. 
if some one ban my main champ i change it and change runes, and next game when i play on main champ i forgot to change runes on main page.
So i change sometimes runes manually but is is too rare. and not  manually configure it.

p.s possible to create program for swap item it the game? i pref heal on 2, active item on mouse5. supp wards on mouse4.
and every time when i buy it i need drag it by my self on this buttons, but main problem is sometimes u forgot to swap it and in team fight u use wrong buttons and it's auto lose fight.

**Comment by sweetriverfish** [comment]
Since this is on the todo list™ and none of the text here provides any meaningful context I'll just close it
