### ISSUE TITLE
Instant chat messages only chat once for the first time

### ISSUE THREAD

**Issue by Scopen86** [sweetriverfish/LeagueAutoAccept#25]
Instant chat messages only chat once for the first time you open the program, for the next games it won't chat anything

**Comment by sweetriverfish** [comment]
I'm not able to reproduce so I'm not sure what the issue is

**Comment by Scopen86** [comment]
Hey, I noitice that you have resolved the issue, thank you!

**Comment by sweetriverfish** [comment]
I have not done anything to address this 🤷
