### ISSUE TITLE
question

### ISSUE THREAD

**Issue by trikiman** [sweetriverfish/LeagueAutoAccept#28]
It is possible somehow copy acc nickname and paste into custom app while lol is active? Can u give any tips if it is possible, if not just close this issue.
sorry for this off top

i mean this one 
![image](https://github.com/sweetriverfish/LeagueAutoAccept/assets/39918652/dafdb6a3-9abe-4bf8-8b73-3340f0029b8c)

**Comment by sweetriverfish** [comment]
Send a `GET` request to `lol-summoner/v1/current-summoner`.
If you're asking it within the context of my app, write `string[] profile = LCU.clientRequest("GET", "lol-summoner/v1/current-summoner");` and it should be accessible under `profile[1]`.

**Comment by trikiman** [comment]
Ty, no its own app.
