### ISSUE TITLE
active window

### ISSUE THREAD

**Issue by trikiman** [sweetriverfish/LeagueAutoAccept#29]
it's possible to turn off attention from lol window? every pick, every move this lol insta active, its possible fix?

**Comment by sweetriverfish** [comment]
It is possible but that's beyond the scope/purpose of this project.

**Comment by trikiman** [comment]
not sure, cus with ur program its useful and its help a lot. Without ur program it is no need. So i sure it is good update.
u can easy check mail, watch videos and etc. Same idea u just do more stuff. Not only pee or smth like this.
![image](https://github.com/sweetriverfish/LeagueAutoAccept/assets/39918652/f7035eb6-a7dc-4be8-833a-e014a8b75c41)

**Comment by trikiman** [comment]
> It is possible but that's beyond the scope/purpose of this project.

forgot to quote

**Comment by sweetriverfish** [comment]
The only use case I can see for for what you are suggesting here is botting accounts, which is not the reason this exists. 

The project exists because as a high elo player I often have queues lasting 10-20 minutes, sometimes even higher, and I wanted something to manage the league client if I need to leave the computer for a moment. I later added an instalocker and instant chat messages for all the blind pick abusers, as per requests.

**Comment by trikiman** [comment]
> The only use case I can see for for what you are suggesting here is botting accounts, which is not the reason this exists.
> 
> The project exists because as a high elo player I often have queues lasting 10-20 minutes, sometimes even higher, and I wanted something to manage the league client if I need to leave the computer for a moment. I later added an instalocker and instant chat messages for all the blind pick abusers, as per requests.

![image](https://github.com/sweetriverfish/LeagueAutoAccept/assets/39918652/20c686a8-5484-431b-8435-eae73c1a4485)
 1 like u see im otp and ur programm is the best for otp. 
 2 i hate queue simulator. quick play best what rito add last time, i hope it's transform to ranked some time and pregame lobby will shorter x4 multiply cus all will prelock, pre runes and etc.  wtf im talking about sry.
3 ur program it's smth on middle way where u can do just whatever u want when game dont start. u can full skip this shit with second monitor, but i need to connect it every time. if u have 1 monitor u cant "full skip queue simulator"
4 if u not otp this program useless, but for improving ur skill u need to be otp. its is great tool for beginners. Who don't have 2-4 champion pool. 
5 u can add second champ role, runes, summs it will fix 4 point.

btw I'm member of league partner program i can't use bots. my main acc on ru server
