### ISSUE TITLE
Feature Request: Ban none

### ISSUE THREAD

**Issue by arkdamenen** [sweetriverfish/LeagueAutoAccept#31]
Hello! 
I am that kind of guy, that plays normals and would like everyone to enjoy their champs, thus I ban none. 
Would be awesome if the program could ban "None" automatically.

I have seen it is possible to choose "None" in the ban settings, but since it does not ban anything, I guess "None" in this case, is just nothing to ban (or otherwise program bugs in my case, for whatever reason).

Thank you!

**Comment by sweetriverfish** [comment]
Makes sense, did not consider that. Will later rename None to Unselected and add None as a proper ban option.

**Comment by arkdamenen** [comment]
Thank you once again! ^^

**Comment by sweetriverfish** [comment]
Done, will be released with the next update.
Feel free to compile your own build in the meanwhile.
