### ISSUE TITLE
Implementation problem

### ISSUE THREAD

**Issue by arianemun** [sweetriverfish/LeagueAutoAccept#34]
I downloaded and ran the latest version of the software, but when I run it, the command prompt window opens for a moment and then immediately closes, like a blink. I have done all the Windows updates and software prerequisites installation such as .Net, and tried running all the published versions of this software, but none of them opened properly. Only the initial version, which is “int”, ran but it doesn’t work at all! What should I do?

System specifications:
Processor	12th Gen Intel(R) Core(TM) i5-12400   2.50 GHz
Installed RAM	32.0 GB (31.7 GB usable)
Product ID	00331-10000-00001-AA735
System type	64-bit operating system, x64-based processor

**Comment by sweetriverfish** [comment]
Try to run it via cmd. It will probably tell you what the issue is.

**Comment by arianemun** [comment]
Hey there, i tired running it with cmd but it behave same. i recoreded screen check it out, it runs just like as a blink.

https://github.com/sweetriverfish/LeagueAutoAccept/assets/34703014/88d51ebf-6e2a-432e-a682-7d00582a2d51

**Comment by arianemun** [comment]
yep, needed .NET 7.0. Thanks for helping me <3
