### ISSUE TITLE
Bug: Cursor disapear when hold right arrow key

### ISSUE THREAD

**Issue by mrcyclo** [sweetriverfish/LeagueAutoAccept#35]
**Screen:** Champion selector
**Action:** Hold RIGHT button
**Actual:** The cursor is disapear and program is hanging

![image](https://github.com/sweetriverfish/LeagueAutoAccept/assets/13806369/1931c165-c055-49d6-812c-c0d3829f194e)

**Comment by sweetriverfish** [comment]
Seems to have been caused by https://github.com/sweetriverfish/LeagueAutoAccept/commit/883e7ec134746fa455705cf8edd3835505e78398

**Comment by sweetriverfish** [comment]
Issues solved, thank you

**Comment by mrcyclo** [comment]
Fastest issue resolved I ever posted on github xD
Thanks.
