### ISSUE TITLE
Auto  Queue

### ISSUE THREAD

**Issue by readmynameplease** [sweetriverfish/LeagueAutoAccept#40]
is it possible to auto queue after each and every game automatically?

**Comment by sweetriverfish** [comment]
What purpose will that serve? I'm against botting.

**Comment by readmynameplease** [comment]
so after a game you go in a Queue immediately it's not actually botting you just go in a queue right after a game. similar to accepting the Accept button when it pops up.

**Comment by sweetriverfish** [comment]
Sorry, I just don't see what purpose will this serve outside of botting
