### ISSUE TITLE
feature request: option to disable auto accept after a dodged lobby

### ISSUE THREAD

**Issue by trikiman** [sweetriverfish/LeagueAutoAccept#41]
Sometimes if u in lobby u dont wanna next game if someone dodge. maybe add checkbox where u can off autoaccept game, but autoban, pick and etc still work.

**Comment by sweetriverfish** [comment]
Slightly delayed but I added something like that

**Comment by trikiman** [comment]
> Slightly delayed but I added something like that

ty) thanks for best app for skip queue simulator

**Comment by trikiman** [comment]
p.s do u plan add runes too? like how summoners spells. (this summoners pre set save some my games like 1 every in 5 days where i forgot to change it back but your program do it)
