### ISSUE TITLE
(Question) This app is now "useless"

### ISSUE THREAD

**Issue by Neinndall** [sweetriverfish/LeagueAutoAccept#42]
Since they have removed the "select champions" mode and now there are quick games, this app does not work, what will be its future?

**Comment by sweetriverfish** [comment]
The application was originally made just to accept queue and do nothing else, for the purpose of allowing me, someone who often waits a lot in queue, to pull a brb and not miss queue. This purpose is still there. I don't play quickplay either so that gamemode existing or not is irrelevant to me.
