### ISSUE TITLE
the champion is not locked

### ISSUE THREAD

**Issue by wreczek** [sweetriverfish/LeagueAutoAccept#43]
I dont remember if it worked in previous versions, but in newest version the champion is picked, another is banned but it is not locked and i got 6 minutes ban

**Comment by wreczek** [comment]
it happens from time to time, for example pick order swap triggers this bug, but some other things also do

**Comment by sweetriverfish** [comment]
tbh I have no idea how to reproduce this. are you sure you didn't play around with delay settings or mess something up in a different way?

**Comment by ghost** [comment]
enabling instalock and insta ban works.
