### ISSUE TITLE
I got an account suspension while using this.

### ISSUE THREAD

**Issue by leolyoo** [sweetriverfish/LeagueAutoAccept#44]
I got an account suspension while using this. I really liked the functionality of this. It looks like Riot guideline certification is necessary.

![image](https://github.com/sweetriverfish/LeagueAutoAccept/assets/44722792/f572ac25-5d40-4376-8c79-7fd3043f0e42)

**Comment by sweetriverfish** [comment]
Are you playing on the Korean server? I am pretty sure they do not allow any stuff of this sort or game modifications.

**Comment by leolyoo** [comment]
Yes, I have a Korean server account. However, before I met this app, I was using 2 applications with similar features, and I feel weird because this issue never happened at the time.

[https://www.overwolf.com/app/mao-tou_projects_ltd-mimic]

[https://team-advisor.vercel.app/promo.html]

**Comment by sweetriverfish** [comment]
Presumably these two did contact Riot for approval, something which I did not. Riot is a lot less restrictive on this type of stuff outside of Korea. I'll probably just add a note to not use it in the Korean server.

**Comment by sweetriverfish** [comment]
Well, I have added a note for it. I did not think of someone from Korea using it nor did i think someone would be banned even if they did. I apologize for the inconvenience.
