### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by SabDabz86** [sweetriverfish/LeagueAutoAccept#5]
Is there a possibility you could write out a step by step guide on how to install and use this I've been looking for something like this everywhere and its awesome that you have provided something like this!!

**Comment by SabDabz86** [comment]
> Is there a possibility you could write out a step by step guide on how to install and use this I've been looking for something like this everywhere and its awesome that you have provided something like this!!

Sorry forgot to add a image of the error

![Error](https://user-images.githubusercontent.com/127666622/224544496-54330882-5e77-4e4d-9c4d-180517ae9d57.PNG)

**Comment by sweetriverfish** [comment]
Make sure you have .NET 5 Runtime installed and just run the .exe file which is provided via releases (or compile it yourself via visual studio. If however you compile it yourself, note that the code in the repository is set to use .NET 7)
.NET 5 Runtime (windows x64 installer): https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-5.0.17-windows-x64-installer
Compiled .exe file: https://github.com/sweetriverfish/LeagueAutoAccept/releases/download/v2.6/Leauge.Auto.Accept.exe

**Comment by SabDabz86** [comment]
It works fine now ! I don't know how to use Visual Studio so I will leave that to the professionals.

Thank You!!!
😄
