### ISSUE TITLE
 ERROR:Description = Invalid namespace

### ISSUE THREAD

**Issue by JoJonoob32** [sweetriverfish/LeagueAutoAccept#50]
![{B896EA34-34BC-49C0-B960-EB2E4D747AA1}](https://github.com/user-attachments/assets/65eab984-71a3-462b-9541-57d81cfc3faf)

Please help.

**Comment by sweetriverfish** [comment]
I've got no clue. Try to compile a debug build via visual studio, it might give more info.

**Comment by sweetriverfish** [comment]
I'll close this as I can't really do much and OP doesn't respond or add anything useful
