### ISSUE TITLE
[Suggestion] Show all characters in "Select a champion" if Game Pass is active

### ISSUE THREAD

**Issue by essencesh** [sweetriverfish/LeagueAutoAccept#6]
All characters are unlocked if Riot Games and Xbox Game Pass accounts are linked. 
If it is possible to do that, I would really appreciate it. 
More information: https://www.xbox.com/en-US/xbox-game-pass/riot-games

**Comment by sweetriverfish** [comment]
I don't mind doing this but I don't have an Xbox Game Pass subscription. Could you compile a build and test if it works?

**Comment by sweetriverfish** [comment]
I made a new tree named [xboxgp](https://github.com/sweetriverfish/LeagueAutoAccept/tree/xboxgp) and updated some code. Could you try running it to see if it works as intended?

**Comment by essencesh** [comment]
It just works perfect as intended, thank you! It really helped a lot.

**Comment by sweetriverfish** [comment]
Merged the tree into main then. It will be fixed next version once I'm done working on some other stuff.
