### ISSUE TITLE
Issues with lane calling

### ISSUE THREAD

**Issue by SabDabz86** [sweetriverfish/LeagueAutoAccept#9]
For some reason when I press enter on the app to call my lane, when I type nothing echos and then I hit save nothing happens just goes back to previous screen?

![LOL Accept](https://user-images.githubusercontent.com/127666622/234213727-46dc0ece-1389-4333-a968-9a0e274a5b20.PNG)

**Comment by sweetriverfish** [comment]
I'm not sure I understand the issue/phrasing?
Click enter on `[new message]` > type something > click enter on `save`.
Perhaps I should make the caret visible so it's more clear that you need to write input?

**Comment by SabDabz86** [comment]
It doesn't do anything I type press enter then save it goes back to previous page without doing anything.

https://user-images.githubusercontent.com/127666622/234286488-28ce30c4-8976-4377-b591-53fd9fdaa257.mp4

**Comment by sweetriverfish** [comment]
You do know that you need to write something, yes?

https://user-images.githubusercontent.com/13397494/234299167-36bd331b-bfd1-4ce7-b8e1-4cd2d42b8ab2.mp4

**Comment by SabDabz86** [comment]
Oh like that now I get it thank man appreciate it.
